---
- hosts: all
  gather_facts: false
  vars:
    - uusername: your_user
    - upassword: your_password

  tasks:
  - name: update_root_password
    user:
      name: "{{ uusername }}"
      password: "{{ upassword | password_hash('sha512') }}"
      update_password: always
